# Generated by Django 4.2.7 on 2026-02-26 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('google', 'Google'), ('meta', 'Meta (Facebook/Instagram)'), ('tiktok', 'TikTok'), ('direct', 'Direct/Other')], default='direct', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('country', models.CharField(blank=True, help_text='Country name (e.g., United States)', max_length=100, null=True)),
                ('state', models.CharField(blank=True, help_text='State/Region name (e.g., California)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'analytics_traffic_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
