# Generated by Django 4.2.7 on 2026-02-25 17:51

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address_user_phone_number_user_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInvitation',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(choices=[('super_admin', 'Super Admin'), ('content', 'Content'), ('finance', 'Finance'), ('marketing', 'Marketing'), ('operations', 'Operations'), ('support', 'Support')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('invite_token', models.CharField(max_length=64, unique=True)),
                ('invited_by', models.EmailField(max_length=254)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('admin_name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-invited_at'],
            },
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
