# Generated by Django 4.2.7 on 2026-02-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_admininvitation_alter_user_managers_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('all', 'All Departments'), ('content', 'Content'), ('finance', 'Finance'), ('marketing', 'Marketing'), ('operations', 'Operations'), ('support', 'Support')], max_length=30, null=True),
        ),
    ]
