# Generated by Django 4.2.7 on 2026-02-28 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
    ]
