# Generated by Django 4.2.7 on 2026-03-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override global commission rate. Leave blank to use global default.', max_digits=5, null=True),
        ),
    ]
