# Generated by Django 4.2.7 on 2026-03-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_delivery_latitude_delivery_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStatsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_orders', models.IntegerField(default=0)),
                ('packed', models.IntegerField(default=0)),
                ('shipped', models.IntegerField(default=0)),
                ('exceptions', models.IntegerField(default=0)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
