# Generated by Django 4.2.7 on 2026-03-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_fix_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='ad',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('google', 'Google'), ('tiktok', 'TikTok')], default='facebook', max_length=100),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('scheduled', 'Scheduled'), ('draft', 'Draft'), ('ended', 'Ended')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('upcoming', 'Upcoming')], default='active', max_length=50),
        ),
    ]
