// A comprehensive list of world currencies
export const globalCurrencies = [
    { code: 'USD', name: 'US Dollar ($)' },
    { code: 'EUR', name: 'Euro (€)' },
    { code: 'GBP', name: 'British Pound (£)' },
    { code: 'PKR', name: 'Pakistani Rupee (Rs)' },
    { code: 'PKT', name: 'Pakistani Rupee (PKT)' },
    { code: 'INR', name: 'Indian Rupee (₹)' },
    { code: 'AED', name: 'UAE Dirham (د.إ)' },
    { code: 'SAR', name: 'Saudi Riyal (﷼)' },
    { code: 'AUD', name: 'Australian Dollar (A$)' },
    { code: 'CAD', name: 'Canadian Dollar (C$)' },
    { code: 'CHF', name: 'Swiss Franc (CHF)' },
    { code: 'CNY', name: 'Chinese Yuan (¥)' },
    { code: 'JPY', name: 'Japanese Yen (¥)' },
    { code: 'NZD', name: 'New Zealand Dollar (NZ$)' },
    { code: 'RUB', name: 'Russian Ruble (₽)' },
    { code: 'ZAR', name: 'South African Rand (R)' },
    { code: 'BRL', name: 'Brazilian Real (R$)' },
    { code: 'MXN', name: 'Mexican Peso ($)' },
    { code: 'SGD', name: 'Singapore Dollar (S$)' },
    { code: 'HKD', name: 'Hong Kong Dollar (HK$)' },
    { code: 'SEK', name: 'Swedish Krona (kr)' },
    { code: 'NOK', name: 'Norwegian Krone (kr)' },
    { code: 'DKK', name: 'Danish Krone (kr)' },
    { code: 'KRW', name: 'South Korean Won (₩)' },
    { code: 'TRY', name: 'Turkish Lira (₺)' },
    { code: 'IDR', name: 'Indonesian Rupiah (Rp)' },
    { code: 'MYR', name: 'Malaysian Ringgit (RM)' },
    { code: 'PHP', name: 'Philippine Peso (₱)' },
    { code: 'THB', name: 'Thai Baht (฿)' },
    { code: 'VND', name: 'Vietnamese Dong (₫)' },
    { code: 'PLN', name: 'Polish Zloty (zł)' },
    { code: 'ILS', name: 'Israeli New Shekel (₪)' },
    { code: 'EGP', name: 'Egyptian Pound (E£)' },
    { code: 'NGN', name: 'Nigerian Naira (₦)' },
    { code: 'KES', name: 'Kenyan Shilling (KSh)' },
    { code: 'GHS', name: 'Ghanaian Cedi (GH₵)' },
    { code: 'BDT', name: 'Bangladeshi Taka (৳)' },
    { code: 'LKR', name: 'Sri Lankan Rupee (Rs)' },
    { code: 'NPR', name: 'Nepalese Rupee (Rs)' },
    { code: 'KWD', name: 'Kuwaiti Dinar (KD)' },
    { code: 'BHD', name: 'Bahraini Dinar (BD)' },
    { code: 'OMR', name: 'Omani Rial (OMR)' },
    { code: 'QAR', name: 'Qatari Riyal (QR)' },
];

// A comprehensive list of world languages with standard ISO 639-1 codes
export const globalLanguages = [
    { code: 'en', name: 'English' },
    { code: 'ur', name: 'Urdu (اردو)' },
    { code: 'hi', name: 'Hindi (हिन्दी)' },
    { code: 'ar', name: 'Arabic (العربية)' },
    { code: 'es', name: 'Spanish (Español)' },
    { code: 'fr', name: 'French (Français)' },
    { code: 'de', name: 'German (Deutsch)' },
    { code: 'zh', name: 'Chinese (中文)' },
    { code: 'pt', name: 'Portuguese (Português)' },
    { code: 'ru', name: 'Russian (Русский)' },
    { code: 'ja', name: 'Japanese (日本語)' },
    { code: 'ko', name: 'Korean (한국어)' },
    { code: 'it', name: 'Italian (Italiano)' },
    { code: 'tr', name: 'Turkish (Türkçe)' },
    { code: 'nl', name: 'Dutch (Nederlands)' },
    { code: 'pl', name: 'Polish (Polski)' },
    { code: 'vi', name: 'Vietnamese (Tiếng Việt)' },
    { code: 'id', name: 'Indonesian (Bahasa Indonesia)' },
    { code: 'ms', name: 'Malay (Bahasa Melayu)' },
    { code: 'th', name: 'Thai (ไทย)' },
    { code: 'fa', name: 'Persian (فارسی)' },
    { code: 'bn', name: 'Bengali (বাংলা)' },
    { code: 'pa', name: 'Punjabi (ਪੰਜਾਬੀ/پنجابی)' },
    { code: 'sw', name: 'Swahili (Kiswahili)' },
    { code: 'sv', name: 'Swedish (Svenska)' },
    { code: 'el', name: 'Greek (Ελληνικά)' },
    { code: 'he', name: 'Hebrew (עברית)' },
    { code: 'cs', name: 'Czech (Čeština)' },
    { code: 'ro', name: 'Romanian (Română)' },
    { code: 'hu', name: 'Hungarian (Magyar)' },
    { code: 'uk', name: 'Ukrainian (Українська)' },
    { code: 'fi', name: 'Finnish (Suomi)' },
    { code: 'da', name: 'Danish (Dansk)' },
    { code: 'no', name: 'Norwegian (Norsk)' },
    { code: 'sk', name: 'Slovak (Slovenčina)' },
    { code: 'bg', name: 'Bulgarian (Български)' },
    { code: 'hr', name: 'Croatian (Hrvatski)' },
    { code: 'sr', name: 'Serbian (Српски)' },
    { code: 'sl', name: 'Slovenian (Slovenščina)' },
    { code: 'lt', name: 'Lithuanian (Lietuvių)' },
    { code: 'lv', name: 'Latvian (Latviešu)' },
    { code: 'et', name: 'Estonian (Eesti)' },
    { code: 'tl', name: 'Tagalog (Tagalog)' },
    { code: 'ta', name: 'Tamil (தமிழ்)' },
    { code: 'te', name: 'Telugu (తెలుగు)' },
    { code: 'mr', name: 'Marathi (मराठी)' },
    { code: 'gu', name: 'Gujarati (ગુજરાતી)' },
    { code: 'kn', name: 'Kannada (ಕನ್ನಡ)' },
    { code: 'ml', name: 'Malayalam (മലയാളം)' },
    { code: 'si', name: 'Sinhala (සිංහල)' },
    { code: 'my', name: 'Burmese (မြန်မာ)' },
    { code: 'km', name: 'Khmer (ខ្មែរ)' },
    { code: 'am', name: 'Amharic (አማርኛ)' }
];
